import time
import json
import warnings
from pathlib import Path
import pandas as pd
import numpy as np
import yfinance as yf
import xgboost as xgb

warnings.filterwarnings('ignore')

# --- CONFIGURATION & PATH ARCHITECTURE ---
BASE_DIR = Path(__file__).resolve().parent
MODEL_FILE = BASE_DIR / "trained_sniper_model.json"
PAPER_ACCOUNT_FILE = BASE_DIR / "merrill_simulated_account.json"
TICKERS_FILE = BASE_DIR / "tickers.txt"

# Trading settings
CONFIDENCE_THRESHOLD = 0.55  # Your sniper sweet spot
INITIAL_SIMULATED_CASH = 100000.00
MERRILL_SIMULATED_COMMISSION = 0.00  # Merrill Edge offers $0 online stock trades
POSITION_SIZE_USD = 10000.00  # Allocate $10,000 per triggered trade opportunity

def load_tickers():
    """Reads tickers directly from tickers.txt. Raises an explicit error if missing."""
    if not TICKERS_FILE.exists():
        raise FileNotFoundError(
            f"\n❌ ERROR: '{TICKERS_FILE.name}' was not found in your directory!\n"
            f"The live scanner cannot guess columns. Please create this file before running."
        )
        
    print(f"📖 Synchronizing features directly with local asset manifest: {TICKERS_FILE.name}")
    with TICKERS_FILE.open("r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip() and not line.strip().startswith("#")]

def initialize_or_load_paper_account():
    """Initializes or loads a local JSON ledger simulating a Merrill Edge account balance."""
    if PAPER_ACCOUNT_FILE.exists():
        with PAPER_ACCOUNT_FILE.open("r") as f:
            return json.load(f)
    
    account_state = {
        "account_type": "Merrill Edge Simulated Cash Account",
        "cash_balance": INITIAL_SIMULATED_CASH,
        "portfolio_value": INITIAL_SIMULATED_CASH,
        "active_positions": {},  # Format: {TICKER: {qty, entry_price, timestamp}}
        "completed_trades_log": []
    }
    save_paper_account(account_state)
    return account_state

def save_paper_account(state):
    with PAPER_ACCOUNT_FILE.open("w") as f:
        json.dump(state, f, indent=4)


def print_account_ledger(account):
    """Prints a concise ledger summary of the paper account for the current scanner cycle."""
    print("\n=== PAPER ACCOUNT LEDGER ===")
    print(f"Cash Balance: ${account['cash_balance']:.2f}")
    print(f"Portfolio Value: ${account['portfolio_value']:.2f}")

    if account["active_positions"]:
        print("Active Positions:")
        for ticker, pos in account["active_positions"].items():
            print(
                f"  - {ticker}: {pos['type']} {pos['qty']} shares @ ${pos['entry_price']:.2f} "
                f"(entered {pos['timestamp_entry']})"
            )
    else:
        print("Active Positions: none")

    completed_trades = account["completed_trades_log"]
    if completed_trades:
        print("Recent Trade History:")
        for trade in completed_trades[-5:]:
            print(
                f"  - {trade['ticker']} | {trade['type']} | "
                f"entry ${trade['entry_price']:.2f} | exit ${trade['exit_price']:.2f} | "
                f"net PnL ${trade['net_pnl']:.2f} | {trade['timestamp_exit']}"
            )
    else:
        print("Recent Trade History: none yet")

    print("============================\n")


def fetch_live_market_snapshot(tickers):
    """Downloads recent raw data to reconstruct identical features used during model training."""
    print("📡 Pulling fresh intraday data fragments via yfinance...")
    df_raw = yf.download(tickers=tickers, period="5d", interval="5m", auto_adjust=False, progress=False)
    if df_raw.empty:
        return pd.DataFrame()
    if isinstance(df_raw.columns, pd.MultiIndex):
        df_raw.columns = df_raw.columns.get_level_values(0)
    df_raw = df_raw.reset_index()
    df_raw.rename(columns={"Datetime": "Timestamp"}, inplace=True, errors="ignore")
    return df_raw

def engineer_live_features(df_snapshot, tickers):
    """Pivots and structures live streaming rows to match training matrix inputs."""
    # Pivot flat ticker structures into wide parallel series
    df_pivoted = df_snapshot.pivot(index="Timestamp", columns="Ticker", values="Close")
    df_pivoted.index = pd.to_datetime(df_pivoted.index)
    df_pivoted = df_pivoted.dropna(how="all")
    
    returns = df_pivoted.pct_change()
    
    # We build the live feature row based on the most recent completed 5-minute bar
    live_row = {}
    
    # Hardcoded to search out your model's exact target feature signals
    # Warning: The exact labels here must match the 63 columns generated by your training export script
    for t in tickers:
        if t in returns.columns:
            try:
                # Retain previous 5-minute and 10-minute return lags
                live_row[f"{t}_Lag_5m"] = returns[t].iloc[-1]
                live_row[f"{t}_Lag_10m"] = returns[t].iloc[-2]
                live_row[f"{t}_Self_Lag_5m"] = returns[t].iloc[-1]
                live_row[f"{t}_Self_Lag_10m"] = returns[t].iloc[-2]
                # Rolling volatility signatures
                live_row[f"{t}_RollVol_15m"] = returns[t].tail(3).std()
            except IndexError:
                # Fallback for data gaps
                live_row[f"{t}_Lag_5m"] = 0.0
                live_row[f"{t}_Lag_10m"] = 0.0
                live_row[f"{t}_Self_Lag_5m"] = 0.0
                live_row[f"{t}_Self_Lag_10m"] = 0.0
                live_row[f"{t}_RollVol_15m"] = 0.0

    return pd.DataFrame([live_row]), df_pivoted.iloc[-1].to_dict()

def process_simulated_exits(account, current_prices):
    """Simulates Merrill Edge order execution for exits after a 5-minute holding period."""
    active_positions = list(account["active_positions"].keys())
    if not active_positions:
        return
        
    print("\n⏰ Processing 5-minute bar exit constraints...")
    for ticker in active_positions:
        pos = account["active_positions"][ticker]
        exit_price = current_prices.get(ticker, pos["entry_price"])
        
        # Calculate PnL
        gross_return = (exit_price - pos["entry_price"]) * pos["qty"] if pos["type"] == "BUY" else (pos["entry_price"] - exit_price) * pos["qty"]
        net_return = gross_return - (MERRILL_SIMULATED_COMMISSION * 2)
        
        # Credit cash balance back
        account["cash_balance"] += (pos["qty"] * exit_price) + net_return if pos["type"] == "BUY" else (pos["qty"] * pos["entry_price"]) + net_return
        
        trade_record = {
            "ticker": ticker,
            "type": pos["type"],
            "qty": pos["qty"],
            "entry_price": pos["entry_price"],
            "exit_price": exit_price,
            "net_pnl": round(net_return, 2),
            "timestamp_exit": str(pd.Timestamp.now())
        }
        
        account["completed_trades_log"].append(trade_record)
        del account["active_positions"][ticker]
        print(f"💰 SIMULATED EXIT executed for {ticker} ({trade_record['type']}). Net PnL: ${trade_record['net_pnl']:.2f}")
        print_account_ledger(account)
    
    save_paper_account(account)

def execute_simulated_entry(account, ticker, direction, current_price):
    """Executes a simulated Merrill Edge position entry allocation."""
    if ticker in account["active_positions"]:
        return # Position already active
        
    if account["cash_balance"] < POSITION_SIZE_USD:
        print(f"⚠️ Simulated order skipped: Insufficient cash balance to allocate ${POSITION_SIZE_USD}.")
        return

    qty = int(POSITION_SIZE_USD // current_price)
    if qty == 0: return
    
    account["cash_balance"] -= (qty * current_price)
    account["active_positions"][ticker] = {
        "type": "BUY" if direction == "UP" else "SHORT",
        "qty": qty,
        "entry_price": current_price,
        "timestamp_entry": str(pd.Timestamp.now())
    }
    print(f"🎯 SIMULATED ENTRY: {account['active_positions'][ticker]['type']} {qty} shares of {ticker} at ${current_price:.2f}")
    print_account_ledger(account)
    save_paper_account(account)

def run_scanner_cycle(model, tickers):
    print(f"\n--- Cycle Triggered At: {pd.Timestamp.now()} ---")
    account = initialize_or_load_paper_account()
    
    # 1. Download live ticks
    df_snapshot = fetch_live_market_snapshot(tickers)
    if df_snapshot.empty:
        print("Market data offline or yfinance returned an empty array. Retrying next cycle.")
        return
        
    # 2. Engineer inputs and collect current prices
    X_live, live_prices = engineer_live_features(df_snapshot, tickers)
    
    # 3. Clean up older positions first (5-minute holding constraint rule)
    process_simulated_exits(account, live_prices)
    
    # 4. Query the trained model matrix
    # Fix feature alignment to match the model training spec
    try:
        probas = model.predict_proba(X_live)[0]
        max_idx = np.argmax(probas)
        certainty = probas[max_idx]
    except Exception as e:
        print(f"Featurization alignment error: {e}. Check ticker configuration lists.")
        return

    print(f"📊 Live Signal Probabilities -> Down: {probas[0]:.4f} | Flat: {probas[1]:.4f} | Up: {probas[2]:.4f}")
    
    # 5. Route certainty triggers
    if certainty >= CONFIDENCE_THRESHOLD:
        print(f"🚀 SIGNAL VERIFIED with {certainty*100:.2f}% certainty!")
        
        # Arbitrarily pick one of your high-confidence followers to target for the position
        # Based on your historical output: CRM (follows SNOW) or NOW (follows DDOG)
        target_follower = "CRM" if live_prices.get("SNOW", 0) != 0 else "NOW"
        current_target_price = live_prices.get(target_follower, 0)
        
        if current_target_price > 0:
            if max_idx == 2:  # Up Class
                execute_simulated_entry(account, target_follower, "UP", current_target_price)
            elif max_idx == 0:  # Down Class
                execute_simulated_entry(account, target_follower, "SHORT", current_target_price)
            else:
                print("Signal resolved as flat noise. Position entry skipped.")
    else:
        print(f"⚖️ Signal below your strict {CONFIDENCE_THRESHOLD*100}% threshold. Standing down in Cash.")

    # 6. Recalculate full account valuation metrics
    current_portfolio_value = account["cash_balance"]
    for tk, pos in account["active_positions"].items():
        curr_p = live_prices.get(tk, pos["entry_price"])
        current_portfolio_value += (pos["qty"] * curr_p)
        
    account["portfolio_value"] = round(current_portfolio_value, 2)
    save_paper_account(account)
    print_account_ledger(account)
    
    print(f"\n📈 MERRILL EDGE PAPER ACCOUNT VALUE: ${account['portfolio_value']:.2f} | Liquid Cash: ${round(account['cash_balance'], 2):.2f}")

def main():
    if not MODEL_FILE.exists():
        print(f"Error: Trained model missing at {MODEL_FILE.name}. Run train_model.py first.")
        return
        
    print("=========================================================================")
    print("                INITIALIZING LIVE MERRILL EDGE SIMULATOR ENGINE          ")
    print("=========================================================================")
    
    # Load JSON model configuration into memory
    model = xgb.XGBClassifier()
    model.load_model(MODEL_FILE)
    tickers = load_tickers()
    
    print(f"Loaded Sniper model configuration safely.")
    print("Running system loop thread... Press Ctrl+C to terminate scanner.")
    
    while True:
        # 1. Execute a live snapshot and prediction scan
        try:
            run_scanner_cycle(model, tickers)
        except Exception as e:
            print(f"Critical execution cycle error encountered: {e}")
            
        # 2. Force the system thread to sleep for exactly 5 minutes (300 seconds)
        print("\n💤 Sleeping for 5 minutes until next bar interval...")
        time.sleep(300)